### ISSUE TITLE
remember me?

### ISSUE THREAD

**Issue by TheCanarianDevision** [managemygroup/entertainment#35]
It's not a request for a cheap date... its a request for a little ticky box on the login screen! i watch via TV and it doesnt have the features of a PC and takes hours to type using the remote control and the onscreen KB!!

**Comment by managemygroup** [comment]
Changes made:

- Scrollbars reduced to just browser page and not various sections.
- EPG number tune should auto focus to make entering EPG number easier on TV Browsers
- Created EPG List guide which can be printed if required.
